# ==========================================================================
# CRE WORKFLOW SETTINGS FILE — airspace-verifier
# ==========================================================================
simulation-settings:
  user-workflow:
    workflow-name: "airspace-verifier-simulation"
    deployment-registry: "private"
  workflow-artifacts:
    workflow-path: "./main.ts"
    config-path: "./config.simulation.json"
    secrets-path: "../secrets.yaml"

# ==========================================================================
staging-settings:
  user-workflow:
    workflow-name: "airspace-verifier-staging"
    deployment-registry: "private"
  workflow-artifacts:
    workflow-path: "./main.ts"
    config-path: "./config.staging.json"
    secrets-path: "../secrets.yaml"

# ==========================================================================
production-settings:
  user-workflow:
    workflow-name: "airspace-verifier-production"
  workflow-artifacts:
    workflow-path: "./main.ts"
    config-path: "./config.production.json"
    secrets-path: "../secrets.yaml"
